name: Deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: pip
          cache-dependency-path: setup.py

      - name: Prepare environment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
        run: |
          REPOSITORY_TOKEN=$(aws codeartifact get-authorization-token --domain matdue --domain-owner 512206508224 --query authorizationToken --output text)
          REPOSITORY_URL=$(aws codeartifact get-repository-endpoint --domain matdue --domain-owner 512206508224 --repository common --format pypi --query repositoryEndpoint --output text)
          PIP_REPOSITORY=https://aws:${REPOSITORY_TOKEN}@${REPOSITORY_URL:8}simple/
          echo "TWINE_USERNAME=aws" >> $GITHUB_ENV
          echo "TWINE_PASSWORD=${REPOSITORY_TOKEN}" >> $GITHUB_ENV
          echo "TWINE_REPOSITORY_URL=${REPOSITORY_URL}" >> $GITHUB_ENV
          echo "PIP_REPOSITORY=${PIP_REPOSITORY}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install --index-url $PIP_REPOSITORY --upgrade setuptools wheel
          pip install --index-url $PIP_REPOSITORY -e .[aws]

      - name: Run unit tests
        run: python -m unittest discover -v

      - name: Deploy
        if: github.event_name == 'release'
        run: |
          python setup.py sdist bdist_wheel
          pip install --index-url $PIP_REPOSITORY twine
          twine upload dist/*
